version: '2'
# compose file for installing composer packages using same php image as the others

services:
  install:
    image: ezsystems/php:${PHP_VERSION}-v0
    volumes:
     - ../../:/var/www
     - $COMPOSER_HOME:/home/ez/.composer
    environment:
     - SYMFONY_ENV
     - SYMFONY_DEBUG
    command: /bin/sh -c "composer install --no-progress --no-interaction --prefer-dist"
